flags:
  gloss: 
    glfw: false
    
extra-package-dbs: []
packages:
- '.'
extra-deps:
    - gloss-1.10.1.1
    - gloss-rendering-1.10.1.1
    - pqueue-1.3.1.1
    - hmatrix-tests-0.5.0.0
resolver: lts-6.7
